### ISSUE TITLE
RELEASE version and LICENSE not found

### ISSUE THREAD

**Issue by lyndomiao** [javadelight/delight-graaljs-sandbox#8]
Could you publish a release version and add a license?@mxro

**Comment by mxro** [comment]
Thank you for raising this issue!

LICENSE.TXT added https://github.com/javadelight/delight-graaljs-sandbox/blob/master/LICENSE.TXT 

Note the licenses are also in the POM file:
https://github.com/javadelight/delight-graaljs-sandbox/blob/master/pom.xml#L346

Sorry could you clarify what you mean by release version? The library should already be on Maven Central: https://search.maven.org/search?q=delight-graaljs-sandbox

**Comment by lyndomiao** [comment]
> 

Thank you, Max. I think a release version means a  stable one. I don't  mean the libraies on Maven Central are vulnerable, but I prefer using a release version.<br>
I found there are six release versions in [delight-nashorn-sandbox](https://github.com/javadelight/delight-nashorn-sandbox) , why don't we publish one for delight-graaljs-sandbox?<br>
Thanks again for your reply!

**Comment by mxro** [comment]
Ah that will be easy! Have added a release on GitHub (same as the version currently published on Maven Central)!
